import { addTimeOff, addWorkingHours, removeScheduleRow } from "@/app/beauty/actions";
import { getBeautyProfile, listTimeOff, listWorkingHours } from "@/lib/db/beauty";
import { BeautyError, BeautyField, BeautyHeader, BeautyPanel, beautyInput } from "@/components/beauty/beauty-ui";
const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
export const dynamic = "force-dynamic";
export default async function SchedulePage({ searchParams }: { searchParams: { error?: string } }) {
  const [hours, blocks, profile] = await Promise.all([listWorkingHours(), listTimeOff(), getBeautyProfile()]);
  const formatter = new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: profile.timezone });
  return <main className="mx-auto max-w-4xl px-5 pb-20 pt-6"><BeautyHeader title="Schedule" /><p className="mt-2 text-xs text-stone-500">All times use {profile.timezone}.</p><BeautyError message={searchParams.error} /><div className="mt-6 grid gap-5 md:grid-cols-2"><BeautyPanel><h2 className="font-semibold text-stone-100">Working hours</h2><form action={addWorkingHours} className="mt-4 grid grid-cols-3 gap-2"><select name="weekday" className={beautyInput}>{days.map((day, index) => <option key={day} value={index}>{day}</option>)}</select><input name="start_time" type="time" required className={beautyInput} /><input name="end_time" type="time" required className={beautyInput} /><button className="col-span-3 min-h-[44px] rounded-lg bg-[var(--beauty-primary)] py-2 text-sm font-semibold text-stone-950">Add hours</button></form><ul className="mt-4 divide-y divide-[color:var(--beauty-border)]">{hours.map((item) => <li key={item.id} className="flex justify-between py-2 text-sm text-stone-300"><span>{days[item.weekday]} · {item.start_time.slice(0, 5)}–{item.end_time.slice(0, 5)}</span><form action={removeScheduleRow}><input type="hidden" name="table" value="working_hours" /><input type="hidden" name="id" value={item.id} /><button className="inline-flex min-h-[44px] items-center text-red-300">Remove</button></form></li>)}</ul></BeautyPanel><BeautyPanel><h2 className="font-semibold text-stone-100">Time off</h2><form action={addTimeOff} className="mt-4 grid gap-3"><BeautyField label="Starts"><input name="starts_at" type="datetime-local" required className={beautyInput} /></BeautyField><BeautyField label="Ends"><input name="ends_at" type="datetime-local" required className={beautyInput} /></BeautyField><BeautyField label="Reason"><input name="reason" className={beautyInput} /></BeautyField><button className="min-h-[44px] rounded-lg bg-[var(--beauty-primary)] py-2 text-sm font-semibold text-stone-950">Block time</button></form><ul className="mt-4 divide-y divide-[color:var(--beauty-border)]">{blocks.map((block) => <li key={block.id} className="flex justify-between gap-2 py-2 text-sm text-stone-300"><span>{formatter.format(new Date(block.starts_at))} · {block.reason || "Time off"}</span><form action={removeScheduleRow}><input type="hidden" name="table" value="time_off" /><input type="hidden" name="id" value={block.id} /><button className="inline-flex min-h-[44px] items-center text-red-300">Remove</button></form></li>)}</ul></BeautyPanel></div></main>;
}
